### ISSUE TITLE
Sugestões e feedback!

### ISSUE THREAD

**Issue by samosaara** [gamaacademy/gama-avanade-tryout01#3]
Não sei se realmente se aplica ao tipo de coisa que vocês querem testar, ou se tornaria muito artificial, mas se os testes futuros forem nessa pegada, 'monte esse tal front end desse tal jeito' **eu acho** que ficaria muito melhor e simples, de codar, e de vocês corrigirem se fosse num site de hosting/sandbox front end, (tipo code pen, JSFiddle etc.) eu recomendaria o [StackBlitz](https://stackblitz.com/), pelo hosting, ótima IDE online e workspace bem parecido com o um editor local, e também funciona offline.

O teste em si, achei bem simples, e aprendi bastante sobre bootstrap, e por motivos puramente estéticos eu ainda prefiro o materialize, mas eu achei ambos bem parecidos, ai queria perguntar, o bootstrap vai ser um requisito forte que nem o angular ou nem tanto?

Última coisa, disseram no hangout que estavam preparando um gabarito mais detalhado com zepellin e tal, seria muito ótimo, por que eu achei tosco, desnecessário e muito maçante ficar ajustando número pra deixar parecido. E falando sobre isso, os prints que estão no README.md estão em HiDPI por causa do retina display do mac, e a resolução está umas 2, 3x maior do que 800x600, e aquela fonte também é a San Francisco, padrão, e exclusiva (bem tecnicamente e legalmente falando pelo menos) do mac.

Meu fork, já com o código pronto: [samosaara/gama-avanade-tryout01](https://github.com/samosaara/gama-avanade-tryout01)

Por que é um saco ficar dando clone só pra ver HTML:
![](https://i.imgur.com/xxvktdq.png)
![](https://i.imgur.com/y8dvWMM.png)

**Comment by Rafael159** [comment]
Olá, finalizei o simulado #1, porém não estou conseguindo forkar. Pelo cmd mostra que todas as alterações foram comitadas, porém na minha conta não aparece as mudanças. Alguém sabe dizer o que devo fazer?
